### PR TITLE
improved JuliaInterface documentation

### PR DESCRIPTION
**Pull request by ThomasBreuer**
- use AutoDoc's `extract_examples` (not the deprecated `maketest`)
- fixed `IsArgumentForJuliaFunction`
- added several manual examples
  (and fixed the indentation of explicit `<Example>` elements,
  in order to have testable examples)

### CODE REVIEW

**Comment by fingolfin** [comment]
This looks of course good! But tests fail on Travis with Julia 1.4 in weird ways:

1. we get some diffs due to changed print functions *sigh*:
```
########> Diff in /home/travis/build/oscar-system/GAP.jl/pkg/JuliaInterface/ts\
t/juliainterface01.tst:129
# Input is:
- m;
# Expected output:
<Julia: Array{Int64,1}[[-1, -2], [-3, -4]]>
# But found:
<Julia: [[-1, -2], [-3, -4]]>
########
########> Diff in /home/travis/build/oscar-system/GAP.jl/pkg/JuliaInterface/ts\
t/juliainterface01.tst:131
# Input is:
m + m;
# Expected output:
<Julia: Array{Int64,1}[[2, 4], [6, 8]]>
# But found:
<Julia: [[2, 4], [6, 8]]>
########
```

2. We see a crash in `Singular.jl` (maybe @hannes14 has an idea what's going on?):
```
ERROR: LoadError: LoadError: IOError: realpath: no such file or directory (ENOENT)
Stacktrace:
 [1] uv_error at ./libuv.jl:97 [inlined]
 [2] realpath(::String) at ./path.jl:429
 [3] top-level scope at /home/travis/.julia/packages/Singular/l3jdY/src/LibSingular.jl:5
 [4] include(::Module, ::String) at ./Base.jl:377
 [5] include(::String) at /home/travis/.julia/packages/Singular/l3jdY/src/Singular.jl:1
 [6] top-level scope at /home/travis/.julia/packages/Singular/l3jdY/src/Singular.jl:110
 [7] include(::Module, ::String) at ./Base.jl:377
 [8] top-level scope at none:2
 [9] eval(::Module, ::Any) at ./boot.jl:331
 [10] eval(::Expr) at ./client.jl:449
 [11] top-level scope at ./none:3
in expression starting at /home/travis/.julia/packages/Singular/l3jdY/src/LibSingular.jl:5
in expression starting at /home/travis/.julia/packages/Singular/l3jdY/src/Singular.jl:110
caused by [exception 42]
fatal: error thrown and no exception handler available.
BoundsError(a=Array{Any, (1,)}[(LoadError(at "/home/travis/.julia/packages/Singular/l3jdY/src/Singular.jl" line 110: LoadError(at "/home/travis/.julia/packages/Singular/l3jdY/src/LibSingular.jl" line 5: Base.IOError(msg="realpath: no such file or directory (ENOENT)", code=-2))), Array{Base.StackTraces.StackFrame, (11,)}[
  Base.StackTraces.StackFrame(func=:uv_error, file=Symbol("./libuv.jl"), line=97, linfo=nothing, from_c=false, inlined=true, pointer=0x00007fad26eb8488),
  Base.StackTraces.StackFrame(func=:realpath, file=Symbol("./path.jl"), line=429, linfo=realpath(String), from_c=false, inlined=false, pointer=0x00007fad26eb8488),
  Base.StackTraces.StackFrame(func=Symbol("top-level scope"), file=Symbol("/home/travis/.julia/packages/Singular/l3jdY/src/LibSingular.jl"), line=5, linfo=Core.CodeInfo(code=Array{Any, (6,)}[
  Expr(:call, Base.getproperty, :Libdl, :(:dlext)),
  Expr(:call, :*, "libsingularwrap.", SSAValue(1)),
  Expr(:call, :joinpath, "/home/travis/.julia/packages/Singular/l3jdY/src", "..", "deps", "usr", "lib", SSAValue(2)),
  Expr(:call, :realpath, SSAValue(3)),
  Expr(:call, CxxWrap.CxxWrapCore.wrapmodule, SSAValue(4), :(:define_julia_module), Singular.libSingular, :nothing),
  Expr(:return, nothing)], codelocs=Array{Int32, (6,)}[1, 1, 1, 1, 1, 1], ssavaluetypes=6, ssaflags=Array{UInt8, (0,)}[], method_for_inference_limit_heuristics=nothing, linetable=Array{Any, (1,)}[Core.LineInfoNode(method=Symbol("top-level scope"), file=Symbol("/home/travis/.julia/packages/Singular/l3jdY/src/LibSingular.jl"), line=5, inlined_at=0)], slotnames=Array{Symbol, (0,)}[], slotflags=Array{UInt8, (0,)}[], slottypes=nothing, rettype=Any, parent=nothing, edges=nothing, min_world=0x0000000000000001, max_world=0xffffffffffffffff, inferred=false, inlineable=false, propagate_inbounds=false, pure=false), from_c=false, inlined=false, pointer=0x0000000000000000),
  Base.StackTraces.StackFrame(func=:include, file=Symbol("./Base.jl"), line=377, linfo=include(Module, String), from_c=false, inlined=false, pointer=0x00007fad2752f321),
  Base.StackTraces.StackFrame(func=:include, file=Symbol("/home/travis/.julia/packages/Singular/l3jdY/src/Singular.jl"), line=1, linfo=include(String), from_c=false, inlined=false, pointer=0x00007fad1840feca),
  Base.StackTraces.StackFrame(func=Symbol("top-level scope"), file=Symbol("/home/travis/.julia/packages/Singular/l3jdY/src/Singular.jl"), line=110, linfo=Core.CodeInfo(code=Array{Any, (2,)}[
  Expr(:call, :include, "LibSingular.jl"),
  Expr(:return, nothing)], codelocs=Array{Int32, (2,)}[1, 1], ssavaluetypes=2, ssaflags=Array{UInt8, (0,)}[], method_for_inference_limit_heuristics=nothing, linetable=Array{Any, (1,)}[Core.LineInfoNode(method=Symbol("top-level scope"), file=Symbol("/home/travis/.julia/packages/Singular/l3jdY/src/Singular.jl"), line=110, inlined_at=0)], slotnames=Array{Symbol, (0,)}[], slotflags=Array{UInt8, (0,)}[], slottypes=nothing, rettype=Any, parent=nothing, edges=nothing, min_world=0x0000000000000001, max_world=0xffffffffffffffff, inferred=false, inlineable=false, propagate_inbounds=false, pure=false), from_c=false, inlined=false, pointer=0x0000000000000000),
  Base.StackTraces.StackFrame(func=:include, file=Symbol("./Base.jl"), line=377, linfo=include(Module, String), from_c=false, inlined=false, pointer=0x00007fad2752f321),
```

**Comment by fingolfin** [comment]
The `realpath` call which fails here looks like this (from `src/LibSingular.jl`)
```
@wrapmodule(realpath(joinpath(@__DIR__, "..", "deps", "usr", "lib", "libsingularwrap." * Libdl.dlext)))
```

Ahah, so looking further up in the Travis log, I see this:
```
┌ Error: Error building `Singular`: 
│ -- The C compiler identification is GNU 5.4.0
│
...
│ [ 44%] Building CXX object CMakeFiles/singularwrap.dir/coeffs.cpp.o
│ /usr/lib/ccache/c++  -DJULIA_ENABLE_THREADING -Dsingularwrap_EXPORTS -I/home/travis/.julia/packages/CxxWrap/lDNAy/deps/usr/lib/cmake/JlCxx/../../../include -I/home/travis/.julia/packages/Nemo/J7Y4Z/deps/usr/include -I/home/travis/.julia/packages/Singular/l3jdY/deps/usr/include -I/home/travis/.julia/packages/Singular/l3jdY/deps/usr/include/singular -isystem /home/travis/julia/include/julia -isystem /home/travis/.julia/packages/CxxWrap/lDNAy/deps/usr/include  -std=c++14 -g -fPIC   -std=gnu++1z -o CMakeFiles/singularwrap.dir/coeffs.cpp.o -c /home/travis/.julia/packages/Singular/l3jdY/deps/src/coeffs.cpp
│ In file included from /home/travis/.julia/packages/CxxWrap/lDNAy/deps/usr/include/jlcxx/array.hpp:4:0,
│                  from /home/travis/.julia/packages/CxxWrap/lDNAy/deps/usr/include/jlcxx/jlcxx.hpp:13,
│                  from /home/travis/.julia/packages/Singular/l3jdY/deps/src/includes.h:9,
│                  from /home/travis/.julia/packages/Singular/l3jdY/deps/src/ideals.h:4,
│                  from /home/travis/.julia/packages/Singular/l3jdY/deps/src/ideals.cpp:1:
│ /home/travis/.julia/packages/CxxWrap/lDNAy/deps/usr/include/jlcxx/type_conversion.hpp:203:43: error: expected template-name before ‘<’ token
│  struct IsMirroredType : std::bool_constant<(!std::is_class<T>::value || (std::is_standard_layout<T>::value && std::is_trivial<T>::value)) && !IsSmartPointerType<T>::value>
│                                            ^
│ /home/travis/.julia/packages/CxxWrap/lDNAy/deps/usr/include/jlcxx/type_conversion.hpp:203:43: error: expected ‘{’ before ‘<’ token
│ /home/travis/.julia/packages/CxxWrap/lDNAy/deps/usr/include/jlcxx/type_conversion.hpp:203:43: error: expected unqualified-id before ‘<’ token
│ In file included from /home/travis/.julia/packages/CxxWrap/lDNAy/deps/usr/include/jlcxx/array.hpp:5:0,
│                  from /home/travis/.julia/packages/CxxWrap/lDNAy/deps/usr/include/jlcxx/jlcxx.hpp:13,
│                  from /home/travis/.julia/packages/Singular/l3jdY/deps/src/includes.h:9,
│                  from /home/travis/.julia/packages/Singular/l3jdY/deps/src/ideals.h:4,
│                  from /home/travis/.julia/packages/Singular/l3jdY/deps/src/ideals.cpp:1:
│ /home/travis/.julia/packages/CxxWrap/lDNAy/deps/usr/include/jlcxx/tuple.hpp: In static member function ‘static jl_datatype_t* jlcxx::julia_type_factory<std::tuple<_Elements ...>, jlcxx::TupleTrait>::julia_type()’:
│ /home/travis/.julia/packages/CxxWrap/lDNAy/deps/usr/include/jlcxx/tuple.hpp:85:38: error: expected primary-expression before 
│      if constexpr(!std::is_same<supertype<PointeeT>, PointeeT>::value)
│         ^
│ In file included from /home/travis/.julia/packages/CxxWrap/lDNAy/deps/usr/include/jlcxx/jlcxx.hpp:14:0,
│                  from /home/travis/.julia/packages/Singular/l3jdY/deps/src/singular.cpp:1:
│ /home/travis/.julia/packages/CxxWrap/lDNAy/deps/usr/include/jlcxx/module.hpp: In instantiation of ‘jlcxx::TypeWrapper<T> jlcxx::Module::add_type_internal(const string&, JLSuperT*) [with T = ip_sring; SuperParametersT = jlcxx::ParameterList<>; JLSuperT = _jl_datatype_t; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
│ /home/travis/.julia/packages/CxxWrap/lDNAy/deps/usr/include/jlcxx/module.hpp:1181:48:   required from ‘jlcxx::TypeWrapper<T> jlcxx::Module::add_type(const string&, JLSuperT*) [with T = ip_sring; SuperParametersT = jlcxx::ParameterList<>; JLSuperT = _jl_datatype_t; std::__cxx11::string = std::__cxx11::basic_string<char>]’
│ /home/travis/.julia/packages/Singular/l3jdY/deps/src/singular.cpp:45:39:   required from here
│ /home/travis/.julia/packages/CxxWrap/lDNAy/deps/usr/include/jlcxx/module.hpp:1101:17: error: incomplete type ‘jlcxx::IsMirroredType<ip_sring>’ used in nested name specifier
│    static_assert(!IsMirroredType<T>::value, "Mirrored types (marked with IsMirroredType) can't be added using add_type, map them directly to a struct instead and use map_type or explicitly disable mirroring for this type, e.g. define template<> struct IsMirroredType<Foo> : std::false_type { };");
│                  ^
│ /home/travis/.julia/packages/CxxWrap/lDNAy/deps/usr/include/jlcxx/module.hpp: In instantiation of ‘jlcxx::TypeWrapper<T> jlcxx::Module::add_type_internal(const string&, JLSuperT*) [with T = bigintmat; SuperParametersT = jlcxx::ParameterList<>; JLSuperT = _jl_datatype_t; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
│ /home/travis/.julia/packages/CxxWrap/lDNAy/deps/usr/include/jlcxx/module.hpp:1181:48:   required from ‘jlcxx::TypeWrapper<T> jlcxx::Module::add_type(const string&, JLSuperT*) [with T = bigintmat; SuperParametersT = jlcxx::ParameterList<>; JLSuperT = _jl_datatype_t; std::__cxx11::string = std::__cxx11::basic_string<char>]’
│ /home/travis/.julia/packages/Singular/l3jdY/deps/src/singular.cpp:54:45:   required from here
│ /home/travis/.julia/packages/CxxWrap/lDNAy/deps/usr/include/jlcxx/module.hpp:1101:17: error: incomplete type ‘jlcxx::IsMirroredType<bigintmat>’ used in nested name specifier
│ CMakeFiles/singularwrap.dir/build.make:62: recipe for target 'CMakeFiles/singularwrap.dir/singular.cpp.o' failed
│ make[2]: *** [CMakeFiles/singularwrap.dir/singular.cpp.o] Error 1
│ make[2]: Leaving directory '/home/travis/.julia/packages/Singular/l3jdY/deps/src'
│ CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/singularwrap.dir/all' failed
│ make[1]: *** [CMakeFiles/singularwrap.dir/all] Error 2
│ make[1]: Leaving directory '/home/travis/.julia/packages/Singular/l3jdY/deps/src'
│ Makefile:129: recipe for target 'all' failed
│ make: *** [all] Error 2
│ [ Info: Downloading https://github.com/JuliaPackaging/Yggdrasil/releases/download/GMP-v6.1.2-1/GMP.v6.1.2.x86_64-linux-gnu.tar.gz to /home/travis/.julia/packages/Singular/l3jdY/deps/usr/downloads/GMP.v6.1.2.x86_64-linux-gnu.tar.gz...
│ [ Info: Downloading https://github.com/JuliaPackaging/Yggdrasil/releases/download/MPFR-v4.0.2-1/MPFR.v4.0.2.x86_64-linux-gnu.tar.gz to /home/travis/.julia/packages/Singular/l3jdY/deps/usr/downloads/MPFR.v4.0.2.x86_64-linux-gnu.tar.gz...
│ [ Info: Downloading https://github.com/thofma/Flint2Builder/releases/download/ba0cee/libflint.v0.0.0-ba0ceed35136a2a43441ab9a9b2e7764e38548ea.x86_64-linux-gnu.tar.gz to /home/travis/.julia/packages/Singular/l3jdY/deps/usr/downloads/libflint.v0.0.0-ba0ceed35136a2a43441ab9a9b2e7764e38548ea.x86_64-linux-gnu.tar.gz...
│ [ Info: Downloading https://github.com/thofma/NTLBuilder2/releases/download/v10.5.0-1/libntl.v10.5.0.x86_64-linux-gnu.tar.gz to /home/travis/.julia/packages/Singular/l3jdY/deps/usr/downloads/libntl.v10.5.0.x86_64-linux-gnu.tar.gz...
│ [ Info: Downloading https://github.com/wbhart/SingularBuilder/releases/download/v0.0.6/libsingular.v0.0.6.x86_64-linux-gnu.tar.gz to /home/travis/.julia/packages/Singular/l3jdY/deps/usr/downloads/libsingular.v0.0.6.x86_64-linux-gnu.tar.gz...
│ ERROR: LoadError: failed process: Process(`make VERBOSE=1`, ProcessExited(2)) [2]
│ 
│ Stacktrace:
│  [1] pipeline_error at ./process.jl:525 [inlined]
│  [2] run(::Cmd; wait::Bool) at ./process.jl:440
│  [3] run(::Cmd) at ./process.jl:438
│  [4] top-level scope at /home/travis/.julia/packages/Singular/l3jdY/deps/build.jl:222
│  [5] include(::String) at ./client.jl:439
│  [6] top-level scope at none:5
│ in expression starting at /home/travis/.julia/packages/Singular/l3jdY/deps/build.jl:222
[19:17:20] ######################################################################## 100.0%
[19:17:21] ######################################################################## 100.0%
[19:17:22] ######################################################################## 100.0%
[19:17:23] ######################################################################## 100.0%
[19:17:24] ######################################################################## 100.0%
│ Initializing cmakeRunning cmake
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Operations.jl:892
```

So, this looks like a CxxWrap issue...

**Comment by ThomasBreuer** [comment]
@fingolfin Note that the LoadError happens even in the corresponding passed test with Julia 1.3.

**Comment by ThomasBreuer** [comment]
Concerning the different `show` functions for `Array{Int64,1}[[2, 4], [6, 8]]` in Julia 1.3 and 1.4,
this is not the first such case and this will not be the last one.
In ordinary testfiles, one can try to avoid relying on `show` results, but the examples in questions come from the manual, and here it is difficult to have useful examples without actually showing the objects. I will try to reformulate the examples ...

**Pull request merged**
