### PR TITLE
Fix compatibility with latest GAP master

### LINKED ISSUE #291: GAP.jl broken?
Fresh julia installation.
```julia
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_DEPOT_PATH = /tmp/new

(v1.2) pkg> add GAP
  Updating registry at `/tmp/new/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
 Installed GAPTypes ─ v1.0.0
 Installed GAP ────── v0.2.1
  Updating `/tmp/new/environments/v1.2/Project.toml`
  [c863536a] + GAP v0.2.1
  Updating `/tmp/new/environments/v1.2/Manifest.toml`
  [c863536a] + GAP v0.2.1
  [cd4130c4] + GAPTypes v1.0.0
  Building GAP → `/tmp/new/packages/GAP/JMFDD/deps/build.log`

julia> using GAP
[ Info: Precompiling GAP [c863536a-3901-11e9-33e7-d5cd0df7b904]
Adding path /tmp/new/packages/GAP/JMFDD/gap/.libs to DL_LOAD_PATH
Panic in src/julia_gc.c:756: GAPTypes.jl is not available
```
Fails also with the same error on julia 1.1. I am pretty sure this used to work.

### PR DESCRIPTION
**Pull request by fingolfin**
Fixes #291. 

Sorry for taking so long for a single-line fix *sigh*

### CODE REVIEW

**Comment by thofma** [comment]
Thanks a lot.

**Comment by fingolfin** [comment]
@ThomasBreuer will look into the nightly failures next. Also, I need to figure out a good way to get notifications when the CI tests for this repository start failing -- right now, I simply never see it :/

**Comment by fieker** [comment]
On Wed, Oct 02, 2019 at 02:46:59AM -0700, Max Horn wrote:
> @ThomasBreuer will look into the nightly failures next. Also, I need to figure out a good way to get notifications when the CI tests for this repository start failing -- right now, I simply never see it :/
> 
Complain. Reimer is supposed to monitor this and tell the responsible PI
immediately.

**Comment by fingolfin** [comment]
Sure, @rbehrends should ideally notify me about failures in the central Jenkins tests, too.

But automation always scales better, plus we run the Travis tests here more frequently. So in addition to whatever Reimer and our Jenkins do, I should also notice failures in the Travis tests immediately. Hence I have now configured Travis to email me whenever master of this repository fails to build on Travis. And since we run the tests at least once every 24 hours, thanks to a Travis cron job, that means I should notice quickly.

In addition, there was supposed to be slack notifications that tell us about master failures, but I think they may be broken.

Finally, I'll work on issue #292

**Pull request merged**
