### PR TITLE
[release-0.12] Backport AA compat bump and set version to 0.12.2

### PR DESCRIPTION
**Pull request by lgoettgens**
backports:
- #1075 
- #1078 
- #1081
- #1091 

and the version bump to 0.12.2

**DON'T SQUASH**, please rebase merge!

### CODE REVIEW

**Comment by thofma** [comment]
Not too familiar with the CI status here. Is the failing CI job (GAP master on macOS) expected?

**Comment by lgoettgens** [comment]
> Not too familiar with the CI status here. Is the failing CI job (GAP master on macOS) expected?

On master, everything is green. I now added the backport of #1078 which worked around that particular failure

**Comment by thofma** [comment]
I'll let @fingolfin handle this here, before I click the wrong button

**Comment by fingolfin** [comment]
Argh. This was bot intentional, a script I run to clean out my merged branches misfired.

@lgoettgens can you please restore / resubmit this?

sorry!

**Pull request merged**
