### PR TITLE
Really restore state after GAP.prompt() exits

### LINKED ISSUE #458: GAP.prompt() changes the behavior of julia even after quitting
```julia
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.1 (2020-04-14)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using GAP

julia> a = [ [ 1, 2 ] ]
1-element Array{Array{Int64,1},1}:
 [1, 2]

julia> GAP.Globals.JuliaToGAP(GAP.Globals.IsList,a)
GAP: [ <Julia: [1, 2]> ]

julia> GAP.Globals.JuliaToGAP( GAP.Globals.JuliaToGAP(GAP.Globals.IsList,a) )
ERROR: Error thrown by GAP: Error, Constructor: the first argument must be a filter (not a plain list)

Stacktrace:
 [1] error(::String, ::String) at ./error.jl:42
 [2] error_handler() at /Users/mo/.julia/dev/GAP/src/GAP.jl:93
 [3] call_gap_func(::Main.ForeignGAP.MPtr, ::Main.ForeignGAP.MPtr; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/mo/.julia/dev/GAP/src/ccalls.jl:109
 [4] call_gap_func at /Users/mo/.julia/dev/GAP/src/ccalls.jl:99 [inlined]
 [5] #_#5 at /Users/mo/.julia/dev/GAP/src/ccalls.jl:95 [inlined]
 [6] (::Main.ForeignGAP.MPtr)(::Main.ForeignGAP.MPtr) at /Users/mo/.julia/dev/GAP/src/ccalls.jl:95
 [7] top-level scope at REPL[4]:1

julia> GAP.prompt()
gap>

julia> GAP.Globals.JuliaToGAP( GAP.Globals.JuliaToGAP(GAP.Globals.IsList,a) )
brk>
brk>
Panic in /Users/mo/.julia/artifacts/848f0f318405266896d24d11e4baf5cf7bf3f203/gap-4.11.0/src/gap.c:1743: Caught error at top-most level, probably quit from library loading
```

### PR DESCRIPTION
**Pull request by fingolfin**
Fixes #458

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
The previous CI failures were due to other errors. I have restarted the ci and all current tests are now passing. Nice.

**Comment by mohamed-barakat** [comment]
I notice that you are trying to get a linear history:
```
(master)$ git pull
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), 233 bytes | 233.00 KiB/s, done.
From https://github.com/oscar-system/GAP.jl
   9a2becf..b415f97  master     -> origin/master
Updating 9a2becf..b415f97
Fast-forward
 src/GAP.jl | 5 ++---
 1 file changed, 2 insertions(+), 3 deletions(-)
(master)$ git branch -d pr-459
error: The branch 'pr-459' is not fully merged.
If you are sure you want to delete it, run 'git branch -D pr-459'.
```
I just want to remark that in contrast to a merge we are losing a commit (and its history) for which the tests have succeeded.

**Comment by fingolfin** [comment]
We have been using `rebase` for GAP.jl since basically forever, just as we do for GAP. There are pros and cons to this. We are aware.

**Comment by mohamed-barakat** [comment]
Thanks for the clarification.

**Comment by mohamed-barakat** [comment]
I have a technical question. It is written [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#rebase-and-merge-your-pull-request-commits) that *"Pull requests with rebased commits are merged using the fast-forward option"*. However, when I tried merging a PR using the `Rebase and merge` option it did not do a fast forward. This is also why I can never `git branch -d pr-???` when testing your PR on `GAP.jl` but have to invoke `git branch -D pr-???`. Did I misunderstand something or is github not complying with its fast-forward promise?

**Pull request merged**
