### PR TITLE
Switch to using GAP_jll

### LINKED ISSUE #285: Feature request: Use BinaryBuilder for GAP.jl

### LINKED ISSUE #433: detect whether JuliaInterface (and GAP.jl) fit to a running GAP
With the current master GAP.jl, the following happens:
I start a GAP that does *not* fit to the master GAP.jl, for example a master GAP,
and erroneously call`LoadPackage( "JuliaInterface" )` at the GAP prompt.
If GAP finds the JuliaInterface of the master GAP.jl then the following message appears.
```
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Building GAP → `/.../pkg/GAP.jl/deps/build.log`
```
Apparently GAP.jl has noticed (at the beginning of `src/GAP.jl`) that the GAP in question does not fit to it, and now it tries to build GAP.
This cannot help in the current situation because GAP is already running, thus I think an error message would be appropriate.
Like in the later code in `src/GAP.jl`, one could check whether `cglobal("GAP_Initialize")` runs into an error, and signal an error if the global variable exists.

Ideally, one would wish that the `AvailabilityTest` function of JuliaInterface checks whether the current GAP and the intended GAP.jl fit together.
This function knows the GAP root paths and the Julia version, but can it safely assume that it finds the interesting files in `../../deps`? (This seems to work even with symbolic links to package directories.)
If yes then the `AvailabilityTest` function of JuliaInterface could check whether the relevant `deps-...` file is available and contains a valid root path of the running GAP, and could signal nonavailability if not.

I can provide a pull request if this sounds sensible.

### LINKED ISSUE #465: GAP.prompt() broken in ubuntu docker container
```
julia> GAP.prompt()
gap> gap> 1+1;
2
gap> gap>
```
After pressing `^L` one prompt vanishes but the double prompt reappears again after next ENTER.

### LINKED ISSUE #518: ordering of initialization steps
GAP.jl's initialization depends on libgap's `GAP_Initialize`, which runs GAP's initialization.
In particular, autoloading GAP packages is part of this process.
Only afterwards, GAP.jl loads the GAP package JuliaInterface.

As soon as one wants to autoload JuliaInterface (not very likely) or a GAP package that depends on JuliaInterface (might become more likely), calling `using GAP` runs into the following problem.
```
WARNING: using GAP.GAP in module Main conflicts with an existing identifier.
ERROR: importing GAP into Main conflicts with an existing identifier
```
This happens after the execution of the `__init__` function of GAP.jl.

Do we have to forbid autoloading JuliaInterface and related packages?

### PR DESCRIPTION
**Pull request by fingolfin**
Incomplete and with several issue, some really bad, but I wanted to have it here for reference

Closes #421
Closes #450 
Closes #468
Closes #548
Closes #564 

Resolves #518
Resolves #285
Fixes #465
Resolves #433 (well, arguably at least, via our custom gaproot)

### CODE REVIEW

**Comment by fingolfin** [comment]
One perk of using GAP_jll is that running the real `gap` executable (which is bundled with `GAP_jll`) is possible again with relative ease. 

But in general, it might be a bit tricky is to keep both Julia-from-GAP and GAP-from-Julia working. As such, we might still want to keep the "fake" GAP executable `gap.sh` (which simulates GAP via Julia). Not sure yet, need to work more on that, just wanted to jot it down here to remind me to not forget about this usecase.

**Comment by fingolfin** [comment]
Seeing this error:
```
Error, LoadError: ArgumentError: Package GAP_jll not found in current path:
- Run `import Pkg; Pkg.add("GAP_jll")` to install the GAP_jll package.

in expression starting at /Users/runner/work/GAP.jl/GAP.jl/src/GAP.jl:7
```

It is caused by this in `pkg/JuliaInterface/read.g`:
```gap
if not IsBound( __JULIAINTERNAL_LOADED_FROM_JULIA ) then
    JuliaEvalString( "Base.MainInclude.include(Base.find_package(\"GAP\"))" );
fi;
```
@ThomasBreuer and me want to get rid of that anyway.... gotta see if I can do it all at once somehow... hrm

**Comment by fingolfin** [comment]
My next plan is to merge PR #548 into this one, and restore PR #557 ; I hope that then in combination, things will work correctly again. We'll see.

(Then the gap.sh mess we discussed on Wednesday still needs to be addressed; I'll open an issue for this later.

**Comment by fingolfin** [comment]
@ThomasBreuer this PR works now for me on all my test systems, and also in the GitHub Actions macOS tests. It fails on the Ubuntu CI tests, though. But I can't reproduce the failure on a Gentoo and an Arch Linux system; unfortunately I don't have access to an Ubuntu system for testing right now  (I'll look into changing this).

But perhaps you can give this branch a try. I still plan some more changes, though.

**Comment by fingolfin** [comment]
@mohamed-barakat @ThomasBreuer this PR is mostly ready. I need to squash a fixup commit and clean up a bit; there is one major thing left to be done:

right now, I (re)create a temporary GAPROOT each time GAP.jl is precompiled. That takes care of a bunch of past issues. But right now, packages are also installed into this transient GAPROOT; that means after a precompilation, your installed GAP packages are gone. To fix this, I'll probably add yet another GAPROOT just for user installed packages which won't be cleaned out by default. Question then is whether there should be ...
1. one global place for GAP packages;
2. one per Julia version
3. one per version of GAP.jl (based on the theory that GAP.jl changes may introduce binary incpompatibilies)
4. ... something else?

**Comment by fingolfin** [comment]
I think this is ready for final review and merging now. I've settled the question on where to install packages for now by "installing" them where we install them right now: inside the GAP source code "artifact". That's not great for various reasons, but it means this PR simply does not affect that particular bit of behavior; so that should remove that point of contention. I've instead opened PR #564 regarding the default package installation path.

**Review by ThomasBreuer — APPROVED** [review]
Thanks a lot.
I think this can be merged.

Some remarks:
- The new `gap.sh` can now be used as is by people (like me) who do not use `bash` --very nice.
- Since there is no `deps/build.jl` anymore, calling `Pkg.build("GAP")` returns without doing anything. This might be irritating for someone who wants to force recompiling GAP this way.
- Perhaps a comment could be added concerning the file `etc/gac`: How is it related to the `gac` file that is generated by GAP's `configure`?

**Review by mohamed-barakat — COMMENTED** [review]
I get the attached error when I run `GAP.Packages.install("io")` logged in `~/.gap/pkg/log/io-4.7.0.log`.

If `GAP.Packages.install` is not supposed to work at the moment then you have my approval.

```
Tue Dec  1 20:50:24 CET 2020

==== Checking io-4.7.0
Running './configure' '--with-gaproot=/Users/mo/.julia/dev/GAP/gaproot/v1.5'
checking for a BSD-compatible install... /usr/local/opt/coreutils/libexec/gnubin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/local/opt/coreutils/libexec/gnubin/mkdir -p
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking build system type... x86_64-apple-darwin20.1.0
checking host system type... x86_64-apple-darwin20.1.0
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/local/opt/gnu-sed/libexec/gnubin/sed
checking for grep that handles long lines and -e... /usr/local/opt/grep/libexec/gnubin/grep
checking for egrep... /usr/local/opt/grep/libexec/gnubin/grep -E
checking for fgrep... /usr/local/opt/grep/libexec/gnubin/grep -F
checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 786432
checking how to convert x86_64-apple-darwin20.1.0 file names to x86_64-apple-darwin20.1.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin20.1.0 file names to toolchain format... func_convert_file_noop
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/local/opt/coreutils/libexec/gnubin/dd
checking how to truncate binary pipes... /usr/local/opt/coreutils/libexec/gnubin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin20.1.0 dyld
checking how to hardcode library paths into programs... immediate
checking for dlopen in -ldl... yes
checking whether a program can dlopen itself... yes
checking whether a statically linked program can dlopen itself... yes
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for GAP root directory... /Users/mo/.julia/dev/GAP/gaproot/v1.5
checking for GAP architecture... checking for GAP >= 4.9... yes
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for ANSI C header files... (cached) yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking netinet/tcp.h usability... yes
checking netinet/tcp.h presence... yes
checking for netinet/tcp.h... yes
checking for stdlib.h... (cached) yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking for unistd.h... (cached) yes
checking signal.h usability... yes
checking signal.h presence... yes
checking for signal.h... yes
checking for an ANSI C-conforming const... yes
checking for pid_t... yes
checking for struct stat.st_blksize... yes
checking for struct stat.st_blocks... yes
checking for struct stat.st_rdev... yes
checking whether time.h and sys/time.h may both be included... yes
checking for uid_t in sys/types.h... yes
checking for unistd.h... (cached) yes
checking for working chown... yes
checking whether closedir returns void... no
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking whether lstat correctly handles trailing slash... no
checking whether lstat accepts an empty string... no
checking whether lstat correctly handles trailing slash... (cached) no
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking for sys/socket.h... (cached) yes
checking types of arguments for select... int,fd_set *,struct timeval *
checking return type of signal handlers... void
checking whether stat accepts an empty string... no
checking for dup2... yes
checking for gethostbyname... yes
checking for lchown... yes
checking for memset... yes
checking for mkdir... yes
checking for mkfifo... yes
checking for rmdir... yes
checking for select... yes
checking for socket... yes
checking for getprotobyname... yes
checking for signal... yes
checking for sigaction... yes
checking for opendir... yes
checking for readdir... yes
checking for closedir... yes
checking for rewinddir... yes
checking for telldir... yes
checking for seekdir... yes
checking for unlink... yes
checking for link... yes
checking for rename... yes
checking for symlink... yes
checking for readlink... yes
checking for accept... yes
checking for bind... yes
checking for chmod... yes
checking for connect... yes
checking for dup... yes
checking for fchmod... yes
checking for fchown... yes
checking for stat... yes
checking for fstat... yes
checking for lstat... yes
checking for getsockopt... yes
checking for listen... yes
checking for lstat... (cached) yes
checking for mknod... yes
checking for mkstemp... yes
checking for mkdtemp... yes
checking for recv... yes
checking for recvfrom... yes
checking for send... yes
checking for sendto... yes
checking for setsockopt... yes
checking for gettimeofday... yes
checking for gmtime... yes
checking for localtime... yes
checking for getpid... yes
checking for getppid... yes
checking for kill... yes
checking for gethostname... yes
checking for getsockname... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/pkgconfig.h
config.status: executing depfiles commands
config.status: executing libtool commands
Running 'make' 'clean'
test -z "io.la" || rm -f io.la
rm -f ./so_locations
rm -rf .libs _libs
rm -rf src/.libs src/_libs
rm -f bin/x86_64-apple-darwin14-julia64-kv7/io.so
rm -f *.o
rm -f src/*.o
rm -f src/*.lo
rm -f *.lo
Running 'make'
  CC       src/io_la-io.lo
  CCLD     io.la
ld: file not found: @rpath/libjulia.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [io.la] Error 1

WARNING: Failed to build io-4.7.0
```

**Comment by mohamed-barakat** [comment]
I went through the details of the PR. Thank you very much for the excellent work.

**Comment by fingolfin** [comment]
@mohamed-barakat Hmm, dang. Unfortunately I cannot reproduce this right now. Which version of Julia is that, precisely? Which macOS version, which Xcode version?

**Comment by mohamed-barakat** [comment]
```
macOS Big Sur, Version 11.0.1 (20B50)
```

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.1 (2020-08-25)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia>
```

```
Xcode Version 12.2 (12B45b)
```

**Comment by fingolfin** [comment]
So, bleeding edge (almost literally 😕) macOS but outdated Julia 😋. Wouldn't surprise me if Apple changed something in an invompatible way, that's what they excel at these days *sigh* I'll try to see if I can come up with another idea

**Comment by mohamed-barakat** [comment]
I made two backups before switching to Gig Sur but to my surprise, it worked smoothly.

FYI: The above problem with the compilation of `io` does not occur with `GAP.jl@master`.

**Comment by fingolfin** [comment]
That they do not occur on GAP.jl master is meaningless, I am afraid.

Can you please attach or add in a comment the content of `gaproot/v1.5/sysinfo.gap`?

**Comment by mohamed-barakat** [comment]
```
# This file has been generated by the GAP build system,
# do not edit manually!
GAPROOTS="/Users/mo/.julia/dev/GAP/src/..;/Users/mo/.julia/dev/GAP/gaproot/v1.5;/Users/mo/.julia/artifacts/6faff9ec58fcefa44d6bacb618a0044d549d091e/share/gap;/Users/mo/.julia/artifacts/848f0f318405266896d24d11e4baf5cf7bf3f203/gap-4.11.0"
GAP_ABI=64
GAP_BIN_DIR="/Users/mo/.julia/dev/GAP/gaproot/v1.5"
GAP_BUILD_VERSION="4.11.0-56-g069a649-dirty"
GAP_CC="gcc"
GAP_CFLAGS=" -g -O2"
GAP_CPPFLAGS="-I/Users/mo/.julia/artifacts/776b19e227382ff3671570cf8b37695efc7cba43/include -I/Users/mo/.julia/artifacts/50127818ecdc20c9948526407e04ae1b124e7bf1/include/gap -I/Users/mo/.julia/dev/GAP/gaproot/v1.5 -DHAVE_CONFIG_H"
GAP_CXX="g++"
GAP_CXXFLAGS=" -g -O2"
GAP_HPCGAP=no
GAP_KERNEL_MAJOR_VERSION=7
GAP_KERNEL_MINOR_VERSION=0
GAP_LDFLAGS="-L/Users/mo/.julia/artifacts/776b19e227382ff3671570cf8b37695efc7cba43/lib -L/Users/mo/.julia/artifacts/50127818ecdc20c9948526407e04ae1b124e7bf1/lib -lgap"
GAP_LIBS="-lgmp -lgap"
GAP_LIB_DIR="/Users/mo/.julia/artifacts/6faff9ec58fcefa44d6bacb618a0044d549d091e/share/gap"
GAP_OBJS="obj/src/ariths.lo obj/src/bags.lo obj/src/blister.lo obj/src/bool.lo obj/src/c_oper1.lo obj/src/c_type1.lo obj/src/calls.lo obj/src/code.lo obj/src/collectors.lo obj/src/compiler.lo obj/src/compstat.lo obj/src/costab.lo obj/src/cyclotom.lo obj/src/debug.lo obj/src/dt.lo obj/src/dteval.lo obj/src/error.lo obj/src/exprs.lo obj/src/ffdata.lo obj/src/finfield.lo obj/src/funcs.lo obj/src/gap.lo obj/gen/gap_version.lo obj/src/gvars.lo obj/src/hookintrprtr.lo obj/src/info.lo obj/src/integer.lo obj/src/intfuncs.lo obj/src/intrprtr.lo obj/src/io.lo obj/src/iostream.lo obj/src/libgap-api.lo obj/src/listfunc.lo obj/src/listoper.lo obj/src/lists.lo obj/src/macfloat.lo obj/src/modules.lo obj/src/modules_builtin.lo obj/src/objcftl.lo obj/src/objects.lo obj/src/objfgelm.lo obj/src/objpcgel.lo obj/src/objset.lo obj/src/opers.lo obj/src/permutat.lo obj/src/plist.lo obj/src/pperm.lo obj/src/precord.lo obj/src/profile.lo obj/src/range.lo obj/src/rational.lo obj/src/read.lo obj/src/records.lo obj/src/saveload.lo obj/src/scanner.lo obj/src/sctable.lo obj/src/set.lo obj/src/stats.lo obj/src/streams.lo obj/src/stringobj.lo obj/src/syntaxtree.lo obj/src/sysfiles.lo obj/src/sysmem.lo obj/src/system.lo obj/src/tietze.lo obj/src/trans.lo obj/src/vars.lo obj/src/vec8bit.lo obj/src/vecffe.lo obj/src/vecgf2.lo obj/src/vector.lo obj/src/weakptr.lo obj/src/julia_gc.lo"
GAP_VERSION="4.11.0"
GAParch=x86_64-apple-darwin14-julia64-kv7
JULIA="/Applications/Julia-1.5.app/Contents/Resources/julia/bin/julia"
JULIA_CPPFLAGS="-std=gnu99 -I/Applications/Julia-1.5.app/Contents/Resources/julia/include/julia -fPIC"
JULIA_LDFLAGS="-L/Applications/Julia-1.5.app/Contents/Resources/julia/lib"
JULIA_LIBS="-Wl,-rpath,/Applications/Julia-1.5.app/Contents/Resources/julia/lib -ljulia"
```

**Comment by fingolfin** [comment]
@mohamed-barakat thanks! can you please give it another try? If it still doesn't work, please once again attach your sysinfo.gap

**Comment by mohamed-barakat** [comment]
It now works, thank you for the wonderful work 👍🏽

**Comment by fingolfin** [comment]
@mohamed-barakat great :-)


I just noticed that I actually forgot to change the place packages are installed to. And my earlier analysis, in which I claimed that package are installed "inside the GAP source code "artifact", was nonsense. So I still need to tackle that.

**Comment by mohamed-barakat** [comment]
I was also puzzled about that statement, but thought you might be referring to the very original behavior or an intermediate commit. And yes, it would be nice to avoid .gap/pkg if possible 😄

**Review by mohamed-barakat — APPROVED** [review]

**Comment by fingolfin** [comment]
I've now update this to install packages into `~/.julia/gaproot/v4.11/pkg/` (or rather `JULIA_DEPOT/gaproot/v4.11/pkg/`), which should be OK for now.

**Comment by fingolfin** [comment]
I get a weird error in the CI now that I cannot reproduce on my MacBook, nor on a Linux server:
```
packages: Test Failed at /home/runner/work/GAP.jl/GAP.jl/test/packages.jl:7
  Expression: GAP.Packages.install("io", interactive = false)
Stacktrace:
 [1] top-level scope at /home/runner/work/GAP.jl/GAP.jl/test/packages.jl:7
 [2] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1113
 [3] top-level scope at /home/runner/work/GAP.jl/GAP.jl/test/packages.jl:3
packages: Test Failed at /home/runner/work/GAP.jl/GAP.jl/test/packages.jl:8
  Expression: GAP.Packages.remove("io", interactive = false)
Stacktrace:
 [1] top-level scope at /home/runner/work/GAP.jl/GAP.jl/test/packages.jl:8
 [2] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1113
 [3] top-level scope at /home/runner/work/GAP.jl/GAP.jl/test/packages.jl:3
Test Summary: | Pass  Fail  Total
packages      |    3     2      5
ERROR: LoadError: LoadError: Some tests did not pass: 3 passed, 2 failed, 0 errored, 0 broken.
in expression starting at /home/runner/work/GAP.jl/GAP.jl/test/packages.jl:1
in expression starting at /home/runner/work/GAP.jl/GAP.jl/test/runtests.jl:11
ERROR: Package GAP errored during testing
Stacktrace:
 [1] pkgerror(::String, ::Vararg{String,N} where N) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Types.jl:53
 [2] test(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; coverage::Bool, julia_args::Cmd, test_args::Cmd, test_fn::Nothing) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Operations.jl:1510
 [3] test(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; coverage::Bool, test_fn::Nothing, julia_args::Cmd, test_args::Cmd, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/API.jl:316
 [4] #test#68 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/API.jl:297 [inlined]
 [5] #test#65 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/API.jl:294 [inlined]
 [6] top-level scope at none:1
```

**Comment by fingolfin** [comment]
The failing commands `GAP.Packages.install("io", interactive = false)` print some messages that probably would allow us to figure out what's wrong, but I don't know how to see them; `Test.jl` seems to suppress the output and I know no way to get it anyway. Maybe @rfourquet does?

In the meantime I can try to modify the CI to call `GAP.Packages.install("io", interactive = false)` in some other place so I get the output

**Comment by rfourquet** [comment]
> Test.jl seems to suppress the output and I know no way to get it anyway. Maybe @rfourquet does?

No unfortunalely, I think Test.jl is not supposed to suppress the output...

**Comment by fingolfin** [comment]
I got the log now by editing the CI workflow:
```
#I Getting PackageInfo URLs...
#I  Retrieving PackageInfo.g from https://gap-packages.github.io/io/PackageInfo.g ...
#I  Downloading archive from URL https://github.com/gap-packages/io/releases/download/v4.7.0/io-4.7.0.tar.gz ...
#I  Saved archive to /tmp/tmEYeNyQ/io-4.7.0.tar.gz
#I  Extracting to /home/runner/.julia/gaproot/v4.11/pkg/io-4.7.0 ...
#I  Running compilation script on /home/runner/.julia/gaproot/v4.11/pkg/io-4.7.0 ...
#I  Package availability test failed
#I  (for IO 4.7.0)
```
So that means that it couldn't load the resulting io.so, either because it was not found or because it fails to load something

**Comment by fingolfin** [comment]
OK the crazy thing is that after swapping the two CI steps, while in the first one I get the error I mentioned above, the step I moved down (so the one which was failing before and now is run later) now PASSES. I am flabbergasted

**Comment by ThomasBreuer** [comment]
I can reproduce the problem with

**Comment by fingolfin** [comment]
@ThomasBreuer oh cool. On which Linux distro? Does it manage to compile IO, or fail to do? If it fails, what's the error; if it succeeds, then why can't GAP load it?

**Comment by ThomasBreuer** [comment]
@fingolfin I have Ubuntu 20.04.1 LTS. The printed messages are exactly as in your example above. I will investigate this further (after 8 p.m.).

**Comment by fingolfin** [comment]
Ok I also habe a Ubuntu 20.04 machine at home (gotta put it on the net for remote access). Will try to reproduce the issue there tonight

**Comment by ThomasBreuer** [comment]
The problem in my setup was that something gets *printed* when my `.gap/gaprc` file is read.
After removing the `Print` statements from this file, the installation of the IO package works for me.
(In `BuildPackages.sh`, GAP should be called with `-r` option.)

**Comment by fingolfin** [comment]
I could also reproduce it (?) on my Ubuntu 20.04 machine, because it was still mostly clean... and didn't have GAP installed globally there... and so I got this:
```
$ cat .julia/gaproot/v4.11/pkg/log/io-4.7.0.err
ERROR: LoadError: ArgumentError: Package GAP not found in current path:
- Run `import Pkg; Pkg.add("GAP")` to install the GAP package.

Stacktrace:
[1] require(::Module, ::Symbol) at ./loading.jl:893
[2] include(::Function, ::Module, ::String) at ./Base.jl:380
[3] include(::Module, ::String) at ./Base.jl:368
[4] exec_options(::Base.JLOptions) at ./client.jl:296
[5] _start() at ./client.jl:506
in expression starting at /home/mhorn/Projekte/OSCAR/GAP.jl/gaproot/v1.5/bin/gap.sh:14
```

OK, that makes sense. What I don't yet understand: why didn't this trigger CI failures in this PR before I made those final changes to the `DEFAULT_PKGDIR`?

**Comment by fingolfin** [comment]
After changing gap.sh to use a proper Julia project, the issues go away on my Ubuntu 20.20 machine but still not in the CI... 

I then used https://github.com/marketplace/actions/debugging-with-tmate (which is super cool, BTW) to SSH into the failing GitHub Action run... repeating the failing test run via
```
julia --color=yes --check-bounds=yes --inline=yes --depwarn=yes --project=@. -e 'using Pkg; Pkg.test()'
```
produced... a perfectly fine pass of the test suite. I tried some other ways but was unable to reproduce the issue. What??

**Comment by fingolfin** [comment]
OK, so stupid: adding `mkpath(sysinfo["DEFAULT_PKGDIR"])` fixed the issue: the problem was that thew new pkg install path did not exist during the first start of the new GAP.jl; which meant that GAP didn't add it as a GAPROOT; which meant that packages installed into this directory were not loadable later on.

**Comment by mohamed-barakat** [comment]
Excellent. Thank you for the great job.

**Pull request merged**
